### ISSUE TITLE
Feature Request: Register and enroll command

### ISSUE THREAD

**Issue by DriesVuylsteke** [ceruzaa/Dave#2]
## Register role
Register roles so that Dave can distribute them to users in the server. For example **@Dave registerRole programmer** will add the programmer role to daves pool of roles to distribute. Only roles that the user owns can be added there.

## Enroll role
After roles are registered users can enroll for these roles. This is done by using **@Dave enroll programmer**. If Dave is a distributor he will assign this role to the pinging user. If Dave is a distributor of this role, he'll say that he does not have permission to assign you this role.

## Overview
An overview of all available roles that Dave can distribute can be displayed using **@Dave roles**.

**Comment by dave** [comment]
Hey it's not ideal to use @dave in your commands because it invites me to the comment 😉

**Comment by ceruzaa** [comment]
@dave sorry about that, it just so happens it's the syntax to mention someone in the discord chat software! we'll try to figure a way around it in the future!

**Comment by dave** [comment]
Thanks
